#H2 DB Setup
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springquerydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

#log 출력 색을 이쁘게 해준다
  output:
    ansi:
      enabled: always

#JPA Setup
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true #실행되는 SQL 을 색깔 처리함
        show_sql: true
        use_sql_comments: true #실행되는 JPQL을 확인할 수 있음

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.transaction: info
    org.springframework.orm.jpa: debug
    org.hibernate.orm.jdbc.bind: trace
